ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of DM'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_79 = ', GC_79
      WRITE(*,2) 'GC_83 = ', GC_83
      WRITE(*,2) 'GC_84 = ', GC_84
      WRITE(*,2) 'GC_94 = ', GC_94
      WRITE(*,2) 'GC_114 = ', GC_114
      WRITE(*,2) 'GC_117 = ', GC_117
      WRITE(*,2) 'GC_146 = ', GC_146
      WRITE(*,2) 'GC_157 = ', GC_157
