ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of DM'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_77 = ', GC_77
      WRITE(*,2) 'GC_78 = ', GC_78
      WRITE(*,2) 'GC_83 = ', GC_83
      WRITE(*,2) 'GC_84 = ', GC_84
      WRITE(*,2) 'GC_107 = ', GC_107
      WRITE(*,2) 'GC_124 = ', GC_124
