P1_uux_xchipxchim_xchip_phipxpsi
P1_ccx_xchipxchim_xchip_phipxpsi
P1_ddx_xchipxchim_xchip_phipxpsi
P1_ssx_xchipxchim_xchip_phipxpsi
P2_uux_xchipxchim_xchim_xpsixphim
P2_ccx_xchipxchim_xchim_xpsixphim
P2_ddx_xchipxchim_xchim_xpsixphim
P2_ssx_xchipxchim_xchim_xpsixphim
