# PYTHIA configuration file.
# Generated on Tue 18 Jun 13:15:44 BST 2019 with the user supplied options:
# --prefix=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/pythia8/
# --with-hepmc2=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/hepmc
# --with-hepmc2-include=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/hepmc/include
# --with-gzip=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/zlib
# --with-lhapdf6=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/lhapdf6
# --with-boost=/usr
# --cxx-common='-ldl -fPIC -lstdc++ -DHEPMC2HACK'

# Install directory prefixes.
PREFIX_BIN=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/pythia8//bin
PREFIX_INCLUDE=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/pythia8//include
PREFIX_LIB=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/pythia8//lib
PREFIX_SHARE=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/pythia8//share/Pythia8

# Compilation flags (see ./configure --help for further documentation).
ENABLE_SHARED=false
CXX=g++
CXX_COMMON=-ldl -fPIC -lstdc++ -DHEPMC2HACK
CXX_SHARED=-shared
CXX_SONAME=-Wl,-soname,
LIB_SUFFIX=.so

# EVTGEN configuration.
EVTGEN_USE=false
EVTGEN_BIN=
EVTGEN_INCLUDE=
EVTGEN_LIB=

# FASTJET3 configuration.
FASTJET3_USE=false
FASTJET3_BIN=
FASTJET3_INCLUDE=
FASTJET3_LIB=

# HEPMC2 configuration.
HEPMC2_USE=true
HEPMC2_BIN=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/hepmc/bin
HEPMC2_INCLUDE=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/hepmc/include
HEPMC2_LIB=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/hepmc/lib

# HEPMC3 configuration.
HEPMC3_USE=false
HEPMC3_BIN=
HEPMC3_INCLUDE=
HEPMC3_LIB=

# LHAPDF5 configuration.
LHAPDF5_USE=false
LHAPDF5_BIN=
LHAPDF5_INCLUDE=
LHAPDF5_LIB=

# LHAPDF6 configuration.
LHAPDF6_USE=true
LHAPDF6_BIN=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/lhapdf6/bin
LHAPDF6_INCLUDE=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/lhapdf6/include
LHAPDF6_LIB=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/lhapdf6/lib

# POWHEG configuration.
POWHEG_USE=false
POWHEG_BIN=
POWHEG_INCLUDE=
POWHEG_LIB=

# PROMC configuration.
PROMC_USE=false
PROMC_BIN=
PROMC_INCLUDE=
PROMC_LIB=

# ROOT configuration.
ROOT_USE=false
ROOT_BIN=
ROOT_LIBS=
CXX_ROOT=

# GZIP configuration.
GZIP_USE=true
GZIP_BIN=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/zlib/
GZIP_INCLUDE=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/zlib/include
GZIP_LIB=/home/s1412595/Desktop/SummerProject2019/MG5_aMC_v2_6_5/HEPTools/zlib/lib

# BOOST configuration.
BOOST_USE=true
BOOST_BIN=/usr/bin
BOOST_INCLUDE=/usr/include
BOOST_LIB=/usr/lib

# PYTHON configuration.
PYTHON_USE=false
PYTHON_BIN=
PYTHON_INCLUDE=
PYTHON_LIB=
